#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty/conf $HOME/.config/kitty

rm -f $HOME/.tmux.conf 
ln -s $DOTFILES/tmux/conf/tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.local/bin
rm -f $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim/conf $HOME/.config/nvim
